blank_issues_enabled: false
contact_links:
    - name: More places to get help
      url: https://discord.gg/E7xYNZpcQX
      about: If you can't seem to get into contact with Paraliyzed_evo or Thunderbirdo, please try to get support in the discord server.
